apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sogo.fullname" . }}-conf
  labels:
    {{- include "sogo.labels" . | nindent 4 }}
data:
  sogo.conf: |
  {{- if .Values.config.use_raw -}}
    {{- .Values.config_raw | nindent 4 }}
  {{- else }}
    {
      /* *********************  Main SOGo configuration file  **********************
      *                                                                           *
      * Since the content of this file is a dictionary in OpenStep plist format,  *
      * the curly braces enclosing the body of the configuration are mandatory.   *
      * See the Installation Guide for details on the format.                     *
      *                                                                           *
      * C and C++ style comments are supported.                                   *
      *                                                                           *
      * This example configuration contains only a subset of all available        *
      * configuration parameters. Please see the installation guide more details. *
      *                                                                           *
      * ~sogo/GNUstep/Defaults/.GNUstepDefaults has precedence over this file,    *
      * make sure to move it away to avoid unwanted parameter overrides.          *
      *                                                                           *
      * **************************************************************************/

      /* Database configuration (mysql://, postgresql:// or oracle://) */
      SOGoProfileURL = "{{ .Values.config.database_url }}/sogo_user_profile";
      OCSFolderInfoURL = "{{ .Values.config.database_url }}/sogo_folder_info";
      OCSSessionsFolderURL = "{{ .Values.config.database_url }}/sogo_sessions_folder";

      /* Mail */
      SOGoDraftsFolderName = {{ .Values.config.mail.drafts_folder_name }};
      SOGoSentFolderName = {{ .Values.config.mail.sent_folder_name }};
      SOGoTrashFolderName = {{ .Values.config.mail.trash_folder_name }};
      SOGoJunkFolderName = {{ .Values.config.mail.junk_folder_name }};
      {{- if .Values.config.mail.imap_server }}
      SOGoIMAPServer = {{ .Values.config.mail.imap_server | quote }};
      {{ end -}}
      {{- if .Values.config.mail.sieve_server }}
      SOGoSieveServer = {{ .Values.config.mail.sieve_server | quote }};
      {{ end -}}
      {{- if .Values.config.mail.smtp_server }}
      SOGoSMTPServer = {{ .Values.config.mail.smtp_server | quote }};
      {{ end -}}
      {{- if .Values.config.mail.mail_domain }}
      SOGoMailDomain = {{ .Values.config.mail.mail_domain | quote }};
      {{ end -}}
      {{- if .Values.config.mail.mailing_mechanism }}
      SOGoMailingMechanism = {{ .Values.config.mail.mailing_mechanism | quote }};
      {{ end -}}
      SOGoForceExternalLoginWithEmail = {{ if .Values.config.mail.force_external_login_with_email }}YES{{- else }}NO{{ end -}};
      {{- if .Values.config.mail.mail_spool_path }}
      SOGoMailSpoolPath = {{ .Values.config.mail.mail_spool_path | quote }};
      {{ end }}
      NGImap4ConnectionStringSeparator = {{ .Values.config.mail.imap4_connection_string_separator | quote }};

      /* Notifications */
      //SOGoAppointmentSendEMailNotifications = NO;
      //SOGoACLsSendEMailNotifications = NO;
      //SOGoFoldersSendEMailNotifications = NO;

      /* Authentication */
      //SOGoPasswordChangeEnabled = YES;

      SOGoUserSources = (
      {{- range .Values.config.user_sources }}
        {
        {{- range $key, $value := . }}
          {{ $key }} = {{ $value | quote }};
        {{- end }}
        }
      {{- end }}
      );

      /* Web Interface */
      SOGoPageTitle = {{ .Values.config.interface.page_title | quote }};
      SOGoVacationEnabled = {{ if .Values.config.interface.vacation_enabled }}YES{{- else }}NO{{- end }};
      SOGoForwardEnabled = {{ if .Values.config.interface.forward_enabled }}YES{{- else }}NO{{- end }};
      SOGoSieveScriptsEnabled = {{ if .Values.config.interface.sieve_scripts_enabled }}YES{{- else }}NO{{- end }};
      SOGoMailAuxiliaryUserAccountsEnabled = {{ if .Values.config.interface.mail_auxiliary_user_accounts_enabled }}YES{{- else }}NO{{- end }};
      SOGoTrustProxyAuthentication = {{ if .Values.config.interface.trust_proxy_authentication }}YES{{- else }}NO{{- end }};
      SOGoXSRFValidationEnabled = {{ if .Values.config.interface.xsrf_validation_enabled }}YES{{- else }}NO{{- end }};

      /* General */
      SOGoLanguage = {{ .Values.config.general.language }};
      SOGoTimeZone = {{ .Values.config.general.timezone }};
      //SOGoCalendarDefaultRoles = (
      //  PublicDAndTViewer,
      //  ConfidentialDAndTViewer
      //);
      //SOGoSuperUsernames = (sogo1, sogo2); // This is an array - keep the parens!
      SxVMemLimit = 0;
      //WOPidFile = "/var/run/sogo/sogo.pid";
      WOWorkersCount = {{ .Values.config.general.workers_count }};

      {{ if .Values.config.memcached_host }}
      SOGoMemcachedHost = {{ .Values.config.memcached_host }};
      {{- else -}}
      {{- if .Values.memcached.enabled -}}
      SOGoMemcachedHost = {{ .Release.Name }}-memcached;
      {{- end -}}
      {{- end }}
      
      /* Debug */
      {{- if .Values.config.debug.requests }}
      SOGoDebugRequests = YES;
      {{- end -}}
      {{ if .Values.config.debug.base_url }}
      SoDebugBaseURL = YES;
      {{- end -}}
      {{ if .Values.config.debug.imap }}
      ImapDebugEnabled = YES;
      {{- end -}}
      {{ if .Values.config.debug.ldap }}
      LDAPDebugEnabled = YES;
      {{- end -}}
      {{ if .Values.config.debug.pg }}
      PGDebugEnabled = YES;
      {{- end -}}
      {{ if .Values.config.debug.mysql4 }}
      MySQL4DebugEnabled = YES;
      {{- end -}}
      {{ if .Values.config.debug.ui_x }}
      SOGoUIxDebugEnabled = YES;
      {{- end -}}
      {{ if .Values.config.debug.dont_zip_response }}
      WODontZipResponse = YES;
      {{- end }}

      /* Extra */
      {{ range $key, $value := .Values.config.extra }}
      {{ $key }} = {{ $value | quote }};
      {{ end }}
    }
  {{- end -}}
