apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sogo.fullname" . }}-conf
  labels:
    {{- include "sogo.labels" . | nindent 4 }}
data:
  sogo.conf: |
    {{- .Values.config_raw | nindent 4 }}
